### ISSUE TITLE
Нужно проверять пользовательский ввод.

### ISSUE THREAD

**Issue by antosha417** [LuckyLi0n/prog_golius#1]
https://github.com/LuckyLi0n/prog_golius/blob/69a7d40fa187474492e70521dde7186ea75805b1/graphics/poligone%203.py#L3-L4
А что если пользователь введёт не число, а строку? Что будет если введёт отрицательное число?

**Comment by antosha417** [comment]
https://github.com/LuckyLi0n/prog_golius/blob/dcbbd66240bbf4a929bb71437cb02bce056615c6/%D1%80%D0%BE%D0%B1%D0%BE%D1%82/task.py#L6-L7 тудаже

**Comment by LuckyLi0n** [comment]
убрала пользовательский ввод

**Comment by antosha417** [comment]
Так не пойдёт. Добавь проверки

**Comment by LuckyLi0n** [comment]
> Так не пойдёт. Добавь проверки

Сделала проверку ввода, по-другому не знаю как 
ff733e8f41bea682ef6684954b3199bc48aa49ba
+ исправила по пеп 8
8c57d1bff286290115a944e149f7a268b7386f95

В первом делать проверку не хочу, там пользовательский ввод не был обязателен. Оттуда просто убрала ввод.

**Comment by antosha417** [comment]
Замечательно. Ты осознала насколько больно хорошо обработать пользовательский ввод, ещё что-то почитала про исключения. Обычно эту заботу оставляют всяким фреймворкам.
