### ISSUE TITLE
Черепаха

### ISSUE THREAD

**Issue by LuckyLi0n** [LuckyLi0n/prog_golius#10]
@antosha417
Хочу сдать черепаху (исправлена, чтоб пайчарм не жаловался)
91639b5b7283c82728e454c617d4f89f9f7ca4ff
фракталы
ca30fd476e98995b9f98fb95a789a29a061ca729
исправление снежинки по пеп 8 (но пайчарм все равно жалуется на shadow name) 
83ee170d5a2c1f7fecce9d487956193c568649e7

**Comment by antosha417** [comment]
Закрывай
