### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by antosha417** [LuckyLi0n/prog_golius#5]
Сделай так, чтоб у меня пайчарм не ругался на несоблюдение PEP8. Если не хочешь пайчарм устанавливать можно [pylint](https://www.pylint.org/), например, использовать.

**Comment by LuckyLi0n** [comment]
Исправила везде по PEP8 (пайчарм у меня стоит)

**Comment by antosha417** [comment]
https://github.com/LuckyLi0n/prog_golius/blob/8fcb02f7c48338d53f9818eae31ae326b666ed18/graphics/game.py#L18
что-то тут не нравится мне

**Comment by antosha417** [comment]
https://github.com/LuckyLi0n/prog_golius/blob/8fcb02f7c48338d53f9818eae31ae326b666ed18/Turtle/turtle_9.py#L10
кажется пробел забыла

**Comment by LuckyLi0n** [comment]
@antosha417 
Исправлены ошибки в PEP8
210b1cb085499354cef50362635b4367c2679097
a8c4abf11f509d5b6e507feeffe2291b05433e17
