### ISSUE TITLE
Игра

### ISSUE THREAD

**Issue by LuckyLi0n** [LuckyLi0n/prog_golius#8]
@antosha417
Создана игра 
83673f1da7f4e82c63fe68ad3cde3e0962bcc1c4
Последняя версия исправления
210b1cb085499354cef50362635b4367c2679097

**Comment by antosha417** [comment]
Куча непонятных констант в коде, давай их хорошо назовём?

Почему начальный счёт -1? мне кажется это как-то не хорошо

**Comment by antosha417** [comment]
`i` - плохое имя для глобальной переменной

**Comment by LuckyLi0n** [comment]
@antosha417 
Исправила имя глобальной переменной и счет
31df0675ccc616a5012635990601763f76abad79

**Comment by antosha417** [comment]
перепиши функцию `click` хорошо
Давай ещё хорошо подумаем над названиями переменных.

**Comment by LuckyLi0n** [comment]
@antosha417 Переменные назвала, не понимаю как "хорошо" переписать функцию click.
1f3b612e9e96509421240c579b93923a0929915a

**Comment by antosha417** [comment]
Я вижу там копипасту, убери её

**Comment by antosha417** [comment]
у тебя одинаковые строчки кода в веткаx if и else

**Comment by antosha417** [comment]
Пока ставлю тебе 0,7  за задачу, чтобы поднять поправь код.

**Comment by LuckyLi0n** [comment]
> Я вижу там копипасту, убери её

Исправила  ad1b770fd564dea3c441667011af831b61c37ad4

**Comment by antosha417** [comment]
Закрывай
